// Country name mapping between FAO data and GeoJSON
const countryMapping = {
    // FAO Name -> GeoJSON Name
    'Afghanistan': 'afghanistan',
    'Albania': 'albania',
    'Algeria': 'algeria',
    'Angola': 'angola',
    'Antigua and Barbuda': 'antigua_and_barbuda',
    'Argentina': 'argentina',
    'Armenia': 'armenia',
    'Australia': 'australia',
    'Austria': 'austria',
    'Azerbaijan': 'azerbaijan',
    'Bahamas': 'bahamas',
    'Bahrain': 'bahrain',
    'Bangladesh': 'bangladesh',
    'Barbados': 'barbados',
    'Belarus': 'belarus',
    'Belgium': 'belgium',
    'Belize': 'belize',
    'Benin': 'benin',
    'Bhutan': 'bhutan',
    'Bolivia (Plurinational State of)': 'bolivia',
    'Bosnia and Herzegovina': 'bosnia_and_herzegovina',
    'Botswana': 'botswana',
    'Brazil': 'brazil',
    'Brunei Darussalam': 'brunei',
    'Bulgaria': 'bulgaria',
    'Burkina Faso': 'burkina_faso',
    'Burundi': 'burundi',
    'Cambodia': 'cambodia',
    'Cameroon': 'cameroon',
    'Canada': 'canada',
    'Cape Verde': 'cape_verde',
    'Central African Republic': 'central_african_republic',
    'Chad': 'chad',
    'Chile': 'chile',
    'China': 'china',
    'China, mainland': 'china',
    'Colombia': 'colombia',
    'Comoros': 'comoros',
    'Congo': 'congo',
    'Costa Rica': 'costa_rica',
    'Croatia': 'croatia',
    'Cuba': 'cuba',
    'Cyprus': 'cyprus',
    'Czechia': 'czech_republic',
    'Democratic Republic of the Congo': 'democratic_republic_of_the_congo',
    'Denmark': 'denmark',
    'Djibouti': 'djibouti',
    'Dominica': 'dominica',
    'Dominican Republic': 'dominican_republic',
    'Ecuador': 'ecuador',
    'Egypt': 'egypt',
    'El Salvador': 'el_salvador',
    'Equatorial Guinea': 'equatorial_guinea',
    'Eritrea': 'eritrea',
    'Estonia': 'estonia',
    'Eswatini': 'swaziland',
    'Ethiopia': 'ethiopia',
    'Fiji': 'fiji',
    'Finland': 'finland',
    'France': 'france',
    'Gabon': 'gabon',
    'Gambia': 'gambia',
    'Georgia': 'georgia',
    'Germany': 'germany',
    'Ghana': 'ghana',
    'Greece': 'greece',
    'Grenada': 'grenada',
    'Guatemala': 'guatemala',
    'Guinea': 'guinea',
    'Guinea-Bissau': 'guinea_bissau',
    'Guyana': 'guyana',
    'Haiti': 'haiti',
    'Honduras': 'honduras',
    'Hungary': 'hungary',
    'Iceland': 'iceland',
    'India': 'india',
    'Indonesia': 'indonesia',
    'Iran (Islamic Republic of)': 'iran',
    'Iraq': 'iraq',
    'Ireland': 'ireland',
    'Israel': 'israel',
    'Italy': 'italy',
    'Jamaica': 'jamaica',
    'Japan': 'japan',
    'Jordan': 'jordan',
    'Kazakhstan': 'kazakhstan',
    'Kenya': 'kenya',
    'Kiribati': 'kiribati',
    'Kuwait': 'kuwait',
    'Kyrgyzstan': 'kyrgyzstan',
    'Lao People\'s Democratic Republic': 'laos',
    'Latvia': 'latvia',
    'Lebanon': 'lebanon',
    'Lesotho': 'lesotho',
    'Liberia': 'liberia',
    'Libya': 'libya',
    'Liechtenstein': 'liechtenstein',
    'Lithuania': 'lithuania',
    'Luxembourg': 'luxembourg',
    'Madagascar': 'madagascar',
    'Malawi': 'malawi',
    'Malaysia': 'malaysia',
    'Maldives': 'maldives',
    'Mali': 'mali',
    'Malta': 'malta',
    'Marshall Islands': 'marshall_islands',
    'Mauritania': 'mauritania',
    'Mauritius': 'mauritius',
    'Mexico': 'mexico',
    'Micronesia (Federated States of)': 'micronesia',
    'Republic of Moldova': 'moldova',
    'Monaco': 'monaco',
    'Mongolia': 'mongolia',
    'Montenegro': 'montenegro',
    'Morocco': 'morocco',
    'Mozambique': 'mozambique',
    'Myanmar': 'myanmar',
    'Namibia': 'namibia',
    'Nauru': 'nauru',
    'Nepal': 'nepal',
    'Netherlands': 'netherlands',
    'New Zealand': 'new_zealand',
    'Nicaragua': 'nicaragua',
    'Niger': 'niger',
    'Nigeria': 'nigeria',
    'Democratic People\'s Republic of Korea': 'north_korea',
    'Norway': 'norway',
    'Oman': 'oman',
    'Pakistan': 'pakistan',
    'Palau': 'palau',
    'Panama': 'panama',
    'Papua New Guinea': 'papua_new_guinea',
    'Paraguay': 'paraguay',
    'Peru': 'peru',
    'Philippines': 'philippines',
    'Poland': 'poland',
    'Portugal': 'portugal',
    'Qatar': 'qatar',
    'Romania': 'romania',
    'Russian Federation': 'russia',
    'Rwanda': 'rwanda',
    'Saint Kitts and Nevis': 'saint_kitts_and_nevis',
    'Saint Lucia': 'saint_lucia',
    'Saint Vincent and the Grenadines': 'saint_vincent_and_the_grenadines',
    'Samoa': 'samoa',
    'San Marino': 'san_marino',
    'Sao Tome and Principe': 'sao_tome_and_principe',
    'Saudi Arabia': 'saudi_arabia',
    'Senegal': 'senegal',
    'Serbia': 'serbia',
    'Seychelles': 'seychelles',
    'Sierra Leone': 'sierra_leone',
    'Singapore': 'singapore',
    'Slovakia': 'slovakia',
    'Slovenia': 'slovenia',
    'Solomon Islands': 'solomon_islands',
    'Somalia': 'somalia',
    'South Africa': 'south_africa',
    'Republic of Korea': 'south_korea',
    'South Sudan': 'south_sudan',
    'Spain': 'spain',
    'Sri Lanka': 'sri_lanka',
    'Sudan': 'sudan',
    'Suriname': 'suriname',
    'Sweden': 'sweden',
    'Switzerland': 'switzerland',
    'Syrian Arab Republic': 'syria',
    'Tajikistan': 'tajikistan',
    'United Republic of Tanzania': 'tanzania',
    'Thailand': 'thailand',
    'Timor-Leste': 'east_timor',
    'Togo': 'togo',
    'Tonga': 'tonga',
    'Trinidad and Tobago': 'trinidad_and_tobago',
    'Tunisia': 'tunisia',
    'Turkey': 'turkey',
    'Turkmenistan': 'turkmenistan',
    'Tuvalu': 'tuvalu',
    'Uganda': 'uganda',
    'Ukraine': 'ukraine',
    'United Arab Emirates': 'united_arab_emirates',
    'United Kingdom': 'united_kingdom',
    'United States of America': 'united_states_of_america',
    'Uruguay': 'uruguay',
    'Uzbekistan': 'uzbekistan',
    'Vanuatu': 'vanuatu',
    'Venezuela (Bolivarian Republic of)': 'venezuela',
    'Viet Nam': 'vietnam',
    'Yemen': 'yemen',
    'Zambia': 'zambia',
    'Zimbabwe': 'zimbabwe'
};

// Reverse mapping for lookup
const reverseCountryMapping = {};
Object.keys(countryMapping).forEach(key => {
    reverseCountryMapping[countryMapping[key]] = key;
});

// Function to get GeoJSON country code from FAO country name
function getFAOToGeoJSONMapping(faoCountryName) {
    return countryMapping[faoCountryName] || null;
}

// Function to get FAO country name from GeoJSON country code
function getGeoJSONToFAOMapping(geoJsonCountryCode) {
    return reverseCountryMapping[geoJsonCountryCode] || null;
}

// Function to normalize country names for better matching
function normalizeCountryNameForMapping(countryName) {
    // Handle common variations
    const variations = {
        'USA': 'United States of America',
        'US': 'United States of America',
        'UK': 'United Kingdom',
        'Russia': 'Russian Federation',
        'South Korea': 'Republic of Korea',
        'North Korea': 'Democratic People\'s Republic of Korea',
        'Iran': 'Iran (Islamic Republic of)',
        'Syria': 'Syrian Arab Republic',
        'Venezuela': 'Venezuela (Bolivarian Republic of)',
        'Bolivia': 'Bolivia (Plurinational State of)',
        'Tanzania': 'United Republic of Tanzania',
        'Moldova': 'Republic of Moldova',
        'Laos': 'Lao People\'s Democratic Republic',
        'Vietnam': 'Viet Nam',
        'Czechia': 'Czech Republic',
        'Czech Republic': 'Czechia'
    };
    
    return variations[countryName] || countryName;
}

// Export the mapping functions
window.CountryMapping = {
    getFAOToGeoJSONMapping,
    getGeoJSONToFAOMapping,
    normalizeCountryNameForMapping,
    countryMapping,
    reverseCountryMapping
};

